- uses: lowlighter/metrics@latest
  with:
    # ... other options
    plugin_music: yes
    plugin_music_limit: 3                   # Limit to 4 entries
    plugin_music_playlist: https://open.spotify.com/embed/playlist/3BTWuHN18ZJdH2n1qjk2et # Use extracted playlist link
                                            #   (plugin_music_provider and plugin_music_mode will be set automatically)
